nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs

packageExtensions:
  '@chakra-ui/react@*':
    dependencies:
      '@chakra-ui/styled-system': '*'
  '@chakra-ui/toast@*':
    dependencies:
      '@chakra-ui/styled-system': '*'
  '@devtools-ds/themes@*':
    dependencies:
      'react-dom': '*'
  '@storybook/addon-docs@*':
    dependencies:
      '@babel/core': '*'
      webpack: '*'
  '@storybook/docs-tools@*':
    dependencies:
      react: '*'
      react-dom: '*'
  '@storybook/instrumenter@*':
    dependencies:
      react: '*'
      react-dom: '*'
  '@storybook/mdx1-csf@*':
    dependencies:
      react: '*'
      '@babel/core': '*'
  '@storybook/telemetry@*':
    dependencies:
      react: '*'
      react-dom: '*'
  '@types/react-datepicker@*':
    dependencies:
      react: '*'
      react-dom: '*'
